### Extracting my file

In [18]:
df = pd.read_csv("ProjectSample1.csv")

In [34]:
import pandas as pd
import numpy as np
import re

df = pd.read_excel("Final_Data.xlsx")

In [36]:
df

,Company,Role,Skills,Experience,Location,Salary,Emp_Type,Timings,Posted Date,Source
0,Caterpillar Brazil,Logistics Engineer,"Logistics,Operations,Supply Chain,Mining Engin...",3-7,Hosur,NaN,"Full Time, Permanent",Flexible timing,1 day ago,via naukri.com
1,Caterpillar Brazil,Accountant,"Income Tax,Billing,Taxation,Direct Tax,Process...",3-5,Bengaluru,12L/yr,"Full Time, Permanent",Flexible timing,1 day ago,via naukri.com
2,Caterpillar Brazil,Manager Quality,"Operations,Production Management,Basic,QMS,Lea...",6-11,Chennai,NaN,"Full Time, Permanent",Flexible timing,1 day ago,via naukri.com
3,Caterpillar Brazil,Logistics Integration Lead,"Sales,Procurement,Supply Chain,Data Collection...",15-20,Chhatrapati Sambhajinagar,NaN,"Full Time, Permanent",Flexible timing,1 day ago,via naukri.com
4,Caterpillar Brazil,Manager Software Engineering,"Information Technology,Product Design,Monitori...",6-10,"Chennai, Bengaluru",NaN,"Full Time, Permanent",Flexible timing,1 day ago,via naukri.com
...,...,...,...,...,...,...,...,...,...,...
8315,CMS It Services,Vendor Coordinator,Not Available,1-2,Not Available,NaN,"Full Time, Permanent",Flexible timing,2 weeks ago,via naukri.com
8316,Nexturn,Senior Etl Tester,"Python,SQL,ETL Testing,Informatica,Selenium,ET...",9-14,Not Available,NaN,"Full Time, Permanent",Flexible timing,3+ weeks ago,via naukri.com
8317,Qloron Pvt Ltd,Senior Microsoft Dynamics 365 CE Functional Co...,"Customer Service,Logistics,ERP,Presales,Servic...",6-11,Not Available,NaN,"Full Time, Permanent",Flexible timing,3 weeks ago,via naukri.com
8318,Opkey,Project Manager,"SCM,Oracle,Project Management,Information Tech...",8-13,Not Available,NaN,"Full Time, Permanent",Flexible timing,3 weeks ago,via naukri.com
8319,Nexturn,Senior Automation Tester | Immediate Joiners Only,"Software Testing,Automation,Selenium",6-9,Not Available,NaN,"Full Time, Permanent",Flexible timing,3+ weeks ago,via naukri.com

### Checking Info and Null Values

In [39]:
df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8320 entries, 0 to 8319
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      8320 non-null   object
 1   Role         8320 non-null   object
 2   Skills       8320 non-null   object
 3   Experience   8320 non-null   object
 4   Location     8320 non-null   object
 5   Salary       2034 non-null   object
 6   Emp_Type     8320 non-null   object
 7   Timings      8320 non-null   object
 8   Posted Date  8320 non-null   object
 9   Source       8320 non-null   object
dtypes: object(10)
memory usage: 650.1+ KB

Company           0
Role              0
Skills            0
Experience        0
Location          0
Salary         6286
Emp_Type          0
Timings           0
Posted Date       0
Source            0
dtype: int64

## Removing Duplicates

In [30]:
df = df.drop_duplicates()

In [32]:
df.shape

(6806, 9)

### Cleaning location column

In [228]:
df["Location"] = df["Location"].str.split(",").str[0]

In [230]:
df["Location"].head(10)

0                        Hosur
1                    Bengaluru
2                      Chennai
3    Chhatrapati Sambhajinagar
4                      Chennai
5                      Chennai
6                    Bengaluru
7                      Chennai
8                      Chennai
9                        Hosur
Name: Location, dtype: object

### Cleaning Source Column

In [233]:
df["Source"] = df["Source"].str.replace("via ","")

In [235]:
df["Source"].head(10)

0    naukri.com
1    naukri.com
2    naukri.com
3    naukri.com
4    naukri.com
5    naukri.com
6    naukri.com
7    naukri.com
8    naukri.com
9    naukri.com
Name: Source, dtype: object

### Creating Min_Exp and Max_Exp from Exp column

In [238]:
df["Experience"].str.extract("(\d+)")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hp\AppData\Local\Temp\ipykernel_16432\2770172034.py:1: SyntaxWarning: invalid escape sequence '\d'
  df["Experience"].str.extract("(\d+)")

       0
0      3
1      3
2      6
3     15
4      6
...   ..
8315   1
8316   9
8317   6
8318   8
8319   6

[7498 rows x 1 columns]

In [240]:
df["Min_Exp"] = df["Experience"].str.extract("(\d+)")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hp\AppData\Local\Temp\ipykernel_16432\421392390.py:1: SyntaxWarning: invalid escape sequence '\d'
  df["Min_Exp"] = df["Experience"].str.extract("(\d+)")

In [242]:
df["Max_Exp"] = df["Experience"].str.extract("-(\d+)")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hp\AppData\Local\Temp\ipykernel_16432\3119621153.py:1: SyntaxWarning: invalid escape sequence '\d'
  df["Max_Exp"] = df["Experience"].str.extract("-(\d+)")

### Converting Exp columns to numerical

In [245]:
## Converting Exp columns to numerical
df["Min_Exp"] = pd.to_numeric(df["Min_Exp"])
df["Max_Exp"] = pd.to_numeric(df["Max_Exp"])

### Cleaning Text Column

In [248]:
df["Company"] = df["Company"].str.strip()
df["Role"] = df["Role"].str.strip()
df["Location"] = df["Location"].str.strip()

### Handling missing values in Salary Column

In [251]:
df["Salary"].unique()

array([nan, '12L/yr', '7L/yr', ..., '₹ 27L/yr - 45L/yr',
       '₹ 35.3L/yr - 54L/yr', '28.5L/yr'], dtype=object)

In [253]:
### Removing symbols
df["Salary"] = df["Salary"].astype(str)
df["Salary"] = df["Salary"].str.replace("₹","")
df["Salary"] = df["Salary"].str.replace("L/yr","")

In [259]:
# Handling salary ranges and replacing 
sal_range = df["Salary"].str.extract(r'(\d+\.?\d*)\s*-\s*(\d+\.?\d*)')
sal_range = sal_range.astype(float)
df["Salary"] = sal_range.mean(axis=1)

### Handling missing values in Salary Column

In [263]:
df["Salary"] = pd.to_numeric(df["Salary"])

In [265]:
# Fill salary based on skills
df["Salary"] = df["Salary"].fillna(
    df.groupby(["Role","Min_Exp"])["Salary"].transform("mean")
)

In [267]:
df["Salary"].isna().sum()

5900

In [269]:
# Fill salary based on skills
df["Salary"] = df["Salary"].fillna(
    df.groupby("Skills")["Salary"].transform("mean")
)

In [271]:
df["Salary"].isna().sum()

4683

In [273]:
# Fill remaining values using experience
df["Salary"] = df["Salary"].fillna(
    df.groupby("Min_Exp")["Salary"].transform("mean"))

In [275]:
df["Salary"].isna().sum()

51

In [279]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [281]:
df["Salary"].isna().sum()

0

In [284]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7498 entries, 0 to 8319
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      7498 non-null   object
 1   Role         7498 non-null   object
 2   Skills       7498 non-null   object
 3   Experience   7498 non-null   object
 4   Location     7498 non-null   object
 5   Salary       7498 non-null   float64
 6   Emp_Type     7498 non-null   object
 7   Timings      7498 non-null   object
 8   Posted Date  7498 non-null   object
 9   Source       7498 non-null   object
 10  Min_Exp      7444 non-null   float64
 11  Max_Exp      7444 non-null   float64
dtypes: float64(3), object(9)
memory usage: 761.5+ KB

In [288]:
## Fixsing missing values in exp columns
df["Min_Exp"] = df["Min_Exp"].fillna(df["Min_Exp"].median())
df["Max_Exp"] = df["Max_Exp"].fillna(df["Max_Exp"].median())

In [290]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7498 entries, 0 to 8319
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      7498 non-null   object
 1   Role         7498 non-null   object
 2   Skills       7498 non-null   object
 3   Experience   7498 non-null   object
 4   Location     7498 non-null   object
 5   Salary       7498 non-null   float64
 6   Emp_Type     7498 non-null   object
 7   Timings      7498 non-null   object
 8   Posted Date  7498 non-null   object
 9   Source       7498 non-null   object
 10  Min_Exp      7498 non-null   float64
 11  Max_Exp      7498 non-null   float64
dtypes: float64(3), object(9)
memory usage: 761.5+ KB

In [292]:
df = df.replace(
    ["Not Available","Not available","Not Specified","Not specified","NA","N/A","-"],
    pd.NA
)

In [294]:
df.isna().sum()

Company           0
Role              0
Skills         1652
Experience       54
Location          7
Salary            0
Emp_Type       1709
Timings        1567
Posted Date    1521
Source         1521
Min_Exp           0
Max_Exp           0
dtype: int64

In [298]:
df["Location"] = df["Location"].fillna(df["Location"].mode()[0])

In [302]:
df["Emp_Type"] = df["Emp_Type"].fillna("Not Specified")

In [304]:
df["Timings"] = df["Timings"].fillna("Not Specified")

In [306]:
df["Posted Date"] = df["Posted Date"].fillna(df["Posted Date"].mode()[0])

In [308]:
df["Source"] = df["Source"].fillna("Unknown")

In [310]:
df.isna().sum()

Company           0
Role              0
Skills         1652
Location          0
Salary            0
Emp_Type          0
Timings           0
Posted Date       0
Source            0
Min_Exp           0
Max_Exp           0
dtype: int64

In [312]:
### Removing non it jobs
non_it = [
    "sales","marketing","hr","recruiter",
    "customer support","business development",
    "telecaller","account manager"
]

df = df[~df["Role"].str.lower().str.contains("|".join(non_it), na=False)]

In [324]:
df.shape

(6956, 11)

In [332]:
df = df[[
"Company",
"Role",
"Skills",
"Location",
"Min_Exp",
"Max_Exp",
"Salary",
"Emp_Type",
"Source"
]]

In [334]:
df

,Company,Role,Skills,Location,Min_Exp,Max_Exp,Salary,Emp_Type,Source
0,Caterpillar Brazil,Logistics Engineer,"Logistics,Operations,Supply Chain,Mining Engin...",Hosur,3.0,7.0,11.474826,"Full Time, Permanent",naukri.com
1,Caterpillar Brazil,Accountant,"Income Tax,Billing,Taxation,Direct Tax,Process...",Bengaluru,3.0,5.0,11.474826,"Full Time, Permanent",naukri.com
2,Caterpillar Brazil,Manager Quality,"Operations,Production Management,Basic,QMS,Lea...",Chennai,6.0,11.0,14.403579,"Full Time, Permanent",naukri.com
3,Caterpillar Brazil,Logistics Integration Lead,"Sales,Procurement,Supply Chain,Data Collection...",Chhatrapati Sambhajinagar,15.0,20.0,15.690393,"Full Time, Permanent",naukri.com
4,Caterpillar Brazil,Manager Software Engineering,"Information Technology,Product Design,Monitori...",Chennai,6.0,10.0,14.403579,"Full Time, Permanent",naukri.com
...,...,...,...,...,...,...,...,...,...
8315,CMS It Services,Vendor Coordinator,<NA>,Bengaluru,1.0,2.0,12.745475,"Full Time, Permanent",naukri.com
8316,Nexturn,Senior Etl Tester,"Python,SQL,ETL Testing,Informatica,Selenium,ET...",Bengaluru,9.0,14.0,15.604512,"Full Time, Permanent",naukri.com
8317,Qloron Pvt Ltd,Senior Microsoft Dynamics 365 CE Functional Co...,"Customer Service,Logistics,ERP,Presales,Servic...",Bengaluru,6.0,11.0,14.403579,"Full Time, Permanent",naukri.com
8318,Opkey,Project Manager,"SCM,Oracle,Project Management,Information Tech...",Bengaluru,8.0,13.0,14.876854,"Full Time, Permanent",naukri.com
8319,Nexturn,Senior Automation Tester | Immediate Joiners Only,"Software Testing,Automation,Selenium",Bengaluru,6.0,9.0,14.403579,"Full Time, Permanent",naukri.com

In [336]:
df.to_excel("IT_JOB_MARKET_DATA.xlsx",index=False)

In [338]:
df = df.drop_duplicates()

In [340]:
df

,Company,Role,Skills,Location,Min_Exp,Max_Exp,Salary,Emp_Type,Source
0,Caterpillar Brazil,Logistics Engineer,"Logistics,Operations,Supply Chain,Mining Engin...",Hosur,3.0,7.0,11.474826,"Full Time, Permanent",naukri.com
1,Caterpillar Brazil,Accountant,"Income Tax,Billing,Taxation,Direct Tax,Process...",Bengaluru,3.0,5.0,11.474826,"Full Time, Permanent",naukri.com
2,Caterpillar Brazil,Manager Quality,"Operations,Production Management,Basic,QMS,Lea...",Chennai,6.0,11.0,14.403579,"Full Time, Permanent",naukri.com
3,Caterpillar Brazil,Logistics Integration Lead,"Sales,Procurement,Supply Chain,Data Collection...",Chhatrapati Sambhajinagar,15.0,20.0,15.690393,"Full Time, Permanent",naukri.com
4,Caterpillar Brazil,Manager Software Engineering,"Information Technology,Product Design,Monitori...",Chennai,6.0,10.0,14.403579,"Full Time, Permanent",naukri.com
...,...,...,...,...,...,...,...,...,...
8315,CMS It Services,Vendor Coordinator,<NA>,Bengaluru,1.0,2.0,12.745475,"Full Time, Permanent",naukri.com
8316,Nexturn,Senior Etl Tester,"Python,SQL,ETL Testing,Informatica,Selenium,ET...",Bengaluru,9.0,14.0,15.604512,"Full Time, Permanent",naukri.com
8317,Qloron Pvt Ltd,Senior Microsoft Dynamics 365 CE Functional Co...,"Customer Service,Logistics,ERP,Presales,Servic...",Bengaluru,6.0,11.0,14.403579,"Full Time, Permanent",naukri.com
8318,Opkey,Project Manager,"SCM,Oracle,Project Management,Information Tech...",Bengaluru,8.0,13.0,14.876854,"Full Time, Permanent",naukri.com
8319,Nexturn,Senior Automation Tester | Immediate Joiners Only,"Software Testing,Automation,Selenium",Bengaluru,6.0,9.0,14.403579,"Full Time, Permanent",naukri.com

In [342]:
df["Skills"] = df["Skills"].fillna("Unknown")

C:\Users\hp\AppData\Local\Temp\ipykernel_16432\1675913651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Skills"] = df["Skills"].fillna("Unknown")

In [344]:
df["Skills"] = df["Skills"].fillna("Unknown")

C:\Users\hp\AppData\Local\Temp\ipykernel_16432\1675913651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Skills"] = df["Skills"].fillna("Unknown")

In [346]:
df["Skills"][0]

'Logistics,Operations,Supply Chain,Mining Engineering,Remedy,Analytical\n \n+ 3 more'

In [356]:
df["Skills"] = df["Skills"].str.replace(r"\+\s*\d+\s*more", "",regex=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_16432\2016460453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Skills"] = df["Skills"].str.replace(r"\+\s*\d+\s*more", "",regex=True)

In [358]:
df["Skills"][2]

'Operations,Production Management,Basic,QMS,Lean Manufacturing,Business Communication\n \n'

In [360]:
df["Skills"] = df["Skills"].str.replace("\n", " ")

C:\Users\hp\AppData\Local\Temp\ipykernel_16432\4001021011.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Skills"] = df["Skills"].str.replace("\n", " ")

In [362]:
df["Skills"][2]

'Operations,Production Management,Basic,QMS,Lean Manufacturing,Business Communication   '

In [364]:
df["Skills"] = df["Skills"].str.replace(r"\s*,\s*", ", ", regex=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_16432\263280869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Skills"] = df["Skills"].str.replace(r"\s*,\s*", ", ", regex=True)

In [366]:
df["Skills"][2]

'Operations, Production Management, Basic, QMS, Lean Manufacturing, Business Communication   '

In [370]:
df["Skills"] = df["Skills"].str.strip()

C:\Users\hp\AppData\Local\Temp\ipykernel_16432\3442338470.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Skills"] = df["Skills"].str.strip()

In [372]:
df["Skills"][2]

'Operations, Production Management, Basic, QMS, Lean Manufacturing, Business Communication'

In [388]:
df["Skills"] = df["Skills"].str.lower()

C:\Users\hp\AppData\Local\Temp\ipykernel_16432\1040340421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Skills"] = df["Skills"].str.lower()

In [390]:
df.isna().sum()

Company     0
Role        0
Skills      0
Location    0
Min_Exp     0
Max_Exp     0
Salary      0
Emp_Type    0
Source      0
dtype: int64

In [392]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6806 entries, 0 to 8319
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Company   6806 non-null   object
 1   Role      6806 non-null   object
 2   Skills    6806 non-null   object
 3   Location  6806 non-null   object
 4   Min_Exp   6806 non-null   float64
 5   Max_Exp   6806 non-null   float64
 6   Salary    6806 non-null   float64
 7   Emp_Type  6806 non-null   object
 8   Source    6806 non-null   object
dtypes: float64(3), object(6)
memory usage: 531.7+ KB

In [382]:
df.duplicated().sum()

3

In [384]:
df = df.drop_duplicates()

In [386]:
df.duplicated().sum()

0

In [394]:
df.to_excel("IT_JOB_MARKET_DATA.xlsx",index=False)

In [24]:
df = pd.read_excel("IT_JOB_MARKET_DATA.xlsx")

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6806 entries, 0 to 6805
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Company   6806 non-null   object
 1   Role      6806 non-null   object
 2   Skills    6806 non-null   object
 3   Location  6806 non-null   object
 4   Min_Exp   6806 non-null   int64
 5   Max_Exp   6806 non-null   int64
 6   Salary    6806 non-null   float64
 7   Emp_Type  6806 non-null   object
 8   Source    6806 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 478.7+ KB